export const advises = [
    "Presta atención a los artefactos, nunca se sabe cuando se romperán.",
    "Elige bien cuando usar tus artefactos.",
    "Valora tus monedas.",
    "Sacar un 20 no solo sirve para pelear.",
    "Elige bien cuando arriesgarte a tirar el dado.",
    "Los 'Tomos de Curación' se consumen apenas comprados.",
    "Una vez bajes de piso, no puedes subir.",
    "El carisma es más útil de lo que parece.",
    "Ciertos lentes te darán más control de durabilidad.",
    "Cierta brújula sabrá guiarte.",
    "En un combate, luego de cada tirada, solo uno golpea, el enemigo o tú.",
    "Las opciones te indicarán si estás al lado de una sala especial con un ícono delante.",
    "El nivel del jugador se suma al número de poder de los artefactos seleccionados, usa esas sumas debidamente.",
    "Fallar en la respuesta a la puerta del jefe de un suelo puede ser fatal.",
]