import { router } from "../vite-env";

export const artifacts: router = {
    PickUps: [
        {name: "Tomo de Curación", description: "Efecto de healing al usuario.", _id: "heart-1"},
        {name: "Moneda", description: "Valor de una moneda." , _id: "coins"},
        {name: "Tomo de Curación Mejorada", description: "Efecto de extra healing al usuario.", _id: "heart-2"},
        {name: "Tomo de Curación Maestra", description: "Efecto de master healing al usuario.", _id: "heart-3"},
    ],
    E: [
        { rank: "E",index:0,durability: 99,totalDurability: 99,power: 0,name: "Lámpara de Aceite", description: "Dicen que nadie se animó nunca a entrar a las dungeons solo con esto." },
        { rank: "E",index:1,durability: 7,totalDurability: 7,power: 1,name: "Espada de Madera", description: "Un arma básica de un aprendiz." },
        { rank: "E",index:2,durability: 12,totalDurability: 12,power: 2,name: "Espada de Hierro", description: "Un arma básica de un aventurero." },
        { rank: "E",index:3,durability: 11,totalDurability: 11,power: 1,name: "Daga de Supervivencia", description: "Un arma básica de un aventurero." },
        { rank: "E",index:4,durability: 7,totalDurability: 7,power: 3,name: "Martillo de Combate", description: "Un arma básica de un aventurero." },
        { rank: "E",index:5,durability: 17,totalDurability: 17,power: 2,name: "Arco Simple", description: "Un arma básica de un aventurero." },
        { rank: "E",index:6,durability: 14,totalDurability: 14,power: 1,name: "Escudo de Madera", description: "Un arma básica de un aventurero." },
        { rank: "E",index:7,durability: 5,totalDurability: 5,power: 4,name: "Espada Oxidada", description: "Un arma antigua que ha pasado por multiples batallas." },
        { rank: "E",index:8,durability: 11,totalDurability:11,power: 1,name: "Botas de Cazador", description: "Un arma básica de un aventurero." },
        { rank: "E",index:9,durability: 14,totalDurability:14,power: 2,name: "Manto Común", description: "Un arma básica de un aventurero." },
    ],
    D: [
        { rank: "D",index:10,durability: 14,totalDurability: 14,power: 4,name: "Anillo de Invocación de Bestias", description: "Invoca una bestia para luchar al lado del portador." },
        { rank: "D",index:11,durability: 20,totalDurability: 20,power: 2,name: "Sombrero de Sombras", description: "Permite al portador esconderse en las sombras con facilidad." },
        { rank: "D",index:12,durability: 1,totalDurability: 1,power: 4,name: "Botella de Tormentas", description: "Al abrirla, desata una pequeña tormenta controlada." },
        { rank: "D",index:13,durability: 8,totalDurability: 8,power: 2,name: "Brazaletes de Defensa", description: "Aumentan la clase de armadura del usuario." },
        { rank: "D",index:14,durability: 6,totalDurability: 6,power: 4,name: "Medallón de Protección Mágica", description: "Protege contra hechizos ofensivos de nivel bajo." },
        { rank: "D",index:15,durability: 25,totalDurability: 25,power: 0,cha:1,name: "Medallón del Conquistador", description: "Da más carisma al portador." },
        { rank: "D",index:16,durability: 50,totalDurability: 50,power: 0,name: "Anillo del Camaleón", description: "Permite al portador cambiar su color para camuflarse." },
        { rank: "D",index:17,durability: 5,totalDurability: 5,power: 11,name: "Capa de Invisibilidad", description: "Una capa que otorga invisibilidad temporal al usuario cuando se activa. Duracion de 5 segundos." },
        { rank: "D",index:18,durability: 8,totalDurability: 8,power: 4,name: "Anillo de Protección Menor", description: "Un anillo que proporciona una pequeña bonificación a la clase de armadura del portador." },
        { rank: "D",index:19,durability: 15,totalDurability: 15,power: 5,name: "Espada de Luz", description: "Una espada que emite una luz tenue cuando se desenfunda, útil para iluminar áreas oscuras." },
        { rank: "D",index:20,durability: 10,totalDurability: 10,power: 5,name: "Amuleto de Resistencia", description: "Un amuleto que ofrece resistencia a un tipo de daño (fuego, frío, etc.) por un tiempo limitado." },
        { rank: "D",index:21,durability: 15,totalDurability: 15,power: 6,name: "Guantes de Fuerza", description: "Guantes que aumentan la fuerza del usuario en una cantidad moderada." },
        { rank: "D",index:22,durability: 3,totalDurability: 3,power: 8,name: "Anillo de Escudo", description: "Un anillo que conjura un escudo mágico alrededor del portador cuando se activa." },
        // { ind11x:0,durability: 10,totalDurability: 10,power: 1,name: "Varita de Luz", description: "Una varita que puede emitir luz o deslumbrar a los enemigos en un área pequeña." },
        { rank: "D",index:23,durability: 1,totalDurability: 1,power: 17,name: "Poción de Fuerza", description: "Una poción que aumenta temporalmente la fuerza del usuario." },
        { rank: "D",index:24,durability: 1,totalDurability: 1,power: 12,name: "Poción de Velocidad Básica", description: "Una poción que aumenta la velocidad temporalmente." },
        { rank: "D",index:25,durability: 1,totalDurability: 1,power: 6,name: "Poción de Salto Básica", description: "Una poción que aumenta el salto temporalmente." },
        { rank: "D",index:26,durability: 1,totalDurability: 1,power: 5,name: "Poción de Resistencia al Frío", description: "Una poción que aumenta la resistencia al frio temporalmente." },
        { rank: "D",index:27,durability: 1,totalDurability: 1,power: 7,name: "Poción de Resistencia al Calor", description: "Una poción que aumenta la resistencia al calor temporalmente." },
        // { rank: "D",index:28,durability: 1,totalDurability: 1,power: 0,name: "Poción de Curación Moderada", description: "Una poción que restaura una cantidad significativa de vitalidad." },
        { rank: "D",index:28,durability: 10,totalDurability: 10,power: 1,name: "Ropa de Camuflaje", description: "Ropa que ayuda a ocultarse en entornos naturales, proporcionando bonificaciones a la sigilo." },
        { rank: "D",index:29,durability: 15,totalDurability: 15,power: 8,name: "Escudo de Resistencia", description: "Un escudo que proporciona una bonificación adicional a la resistencia contra ciertos tipos de daño." },
        { rank: "D",index:30,durability: 12,totalDurability: 12,power: 2,name: "Capa de Protección contra el Frío", description: "Una capa que proporciona protección contra el daño por frío y la exposición a temperaturas extremadamente bajas." },
        { rank: "D",index:31,durability: 10,totalDurability: 10,power: 6,name: "Bastón de Maldición Menor", description: "Un bastón que puede maldecir cuando se usa." },
        // { ind31x:0,durability: 10,totalDurability: 10,power: 4,name: "Lentes de Oscuridad", description: "Gafas que permiten al usuario ver en la oscuridad completa." },
        { rank: "D",index:32,durability: 10,totalDurability: 10,power: 6,name: "Escudo de Resplandor", description: "Un escudo que emite un resplandor brillante, deslumbrando a los enemigos cercanos." }
    ],
    C: [
        // { rank: "C",index:0,durability: 10,totalDurability: 10,power: 8,name: "Poción de Saturación", description: "Una poción que elimina la necesidad de comer durante 3 días, nutriendo al usuario perfectamente." },
        // { rank: "C",index:0,durability: 10,totalDurability: 10,power: 8,name: "Poción de Estimulación", description: "Una poción que elimina la necesidad de dormir durante 7 días." },
        { rank: "C",index:33,durability: 1,totalDurability: 1,power: 8,name: "Poción de Sigilo", description: "Una poción que aumenta el sigilo del usuario por meses." },
        { rank: "C",index:34,durability: 1,totalDurability: 1,power: 10,name: "Poción de Salto", description: "Una poción que aumenta temporalmente la potencia de salto del usuario." },
        { rank: "C",index:35,durability: 15,totalDurability: 15,power: 9,name: "Brazaletes de Velocidad", description: "Aumentan la velocidad de movimiento del portador (x0.75)." },
        { rank: "C",index:36,durability: 10,totalDurability: 10,power: 7,name: "Daga de la Sombra", description: "Hace que el portador sea difícil de detectar en la oscuridad." },
        { rank: "C",index:37,durability: 20,totalDurability: 20,power: 10,name: "Espada de Llamas Eternas", description: "Una espada que arde con fuego inextinguible." },
        { rank: "C",index:38,durability: 25,totalDurability: 25,power: 4,name: "Aro de Inmunidad al Veneno", description: "El portador no puede ser envenenado mientras lo lleva." },
        { rank: "C",index:39,durability: 6,totalDurability: 6,power: 9,name: "Capa del Engaño", description: "Crea una imagen duplicada del portador para confundir a los enemigos." },
        { rank: "C",index:40,durability: 12,totalDurability: 12,power: 11,name: "Báculo del Hielo", description: "Lanza tempanos de hielo a gran velocidad." },
        { rank: "C",index:41,durability: 8,totalDurability: 8,power: 12,name: "Báculo del Fuego Infernal", description: "Lanza llamas infernales que queman a los enemigos." },
        { rank: "C",index:42,durability: 18,totalDurability: 18,power: 9,name: "Anillo de Control Elemental", description: "Da al usuario control limitado sobre los elementos naturales. Solo control tipo telequinetico de los elementos." },
        { rank: "C",index:43,durability: 12,totalDurability: 12,power: 13,name: "Espada de la Luz Pura", description: "Causa daño radiante a los enemigos oscuros." },
        { rank: "C",index:44,durability: 20,totalDurability: 20,power: 6,name: "Capa de Niebla", description: "Envuelve al usuario en una espesa niebla que dificulta la visión." },
        { rank: "C",index:45,durability: 22,totalDurability: 22,power: 8,name: "Cinturón del Equilibrio", description: "Evita que el usuario pierda el equilibrio o sea derribado." },
        { rank: "C",index:46,durability: 12,totalDurability: 12,power: 8,name: "Gema de la Paciencia", description: "Otorga serenidad y calma al portador." },
        { rank: "C",index:47,durability: 20,totalDurability: 20,power: 3,name: "Piedra del Silencio", description: "Anula todo sonido en un área pequeña al activarse." },
        { rank: "C",index:48,durability: 40,totalDurability: 40,power: 8,name: "Colgante del Valor", description: "Aumenta la moral del usuario y sus aliados cercanos." },
        { rank: "C",index:49,durability: 20,totalDurability: 20,power: 7,name: "Anillo de la Visión Lejana", description: "Permite ver claramente a grandes distancias como si estuvieras cerca." },
        { rank: "C",index:50,durability: 18,totalDurability: 18,power: 8,name: "Túnica de la Estrella Matutina", description: "Brilla con la luz del amanecer, ahuyentando criaturas oscuras." },
        // { rank: "C",index:0,durability: 20,totalDurability: 20,power: 0,name: "Anillo del Agua", description: "Permite respirar bajo el agua y moverse libremente en ella." },
        { rank: "C",index:51,durability: 3,totalDurability: 3,power: 20,name: "Capa de Plumas", description: "Transforma al portador en un ave durante 7 segundos, con un cooldown de 1 minuto." },
        { rank: "C",index:52,durability: 5,totalDurability: 5,power: 17,name: "Botas de Velocidad del Viento", description: "Permiten al usuario moverse al doble de su velocidad normal." },
        { rank: "C",index:53,durability: 18,totalDurability: 18,power: 13,name: "Espada de las Sombras", description: "Aumenta su poder cuando está en la oscuridad." },
        // { ind5x:0,durability: 10,totalDurability: 10,power: 8,name: "Túnica de las Sombras", description: "Hace que el portador sea difícil de detectar." },
        { rank: "C",index:54,durability: 15,totalDurability: 15,power: 4,name: "Brazalete de la Invocación", description: "Permite al portador invocar tres cuervos con los que comparte visión." },
        // { rank: "C",index:0,durability: 10,totalDurability: 10,power: 8,name: "Sombrero del Somnoliento", description: "Induce un sueño profundo e inmediato en quien lo usa." },
        { rank: "C",index:55,durability: 20,totalDurability: 20,power: 6,name: "Túnica del Desierto", description: "Otorga resistencia a las altas temperaturas y protege contra tormentas de arena." },
        // { rank: "C",index:0,durability: 10,totalDurability: 10,power: 8,name: "Botas de la Montaña", description: "Permiten al portador escalar montañas empinadas con mayor facilidad." },
        { rank: "C",index:56,durability: 20,totalDurability: 20,power: 0,cha:2,name: "Botas de Conquistador", description: "Se sienten comodas y dan más carisma." },
        { rank: "C",index:57,durability: 15,totalDurability: 15,power: 10,name: "Capa del Horizonte", description: "Otorga la capacidad de ver a grandes distancias." },
        // { rank: "C",index:0,durability: 10,totalDurability: 10,power: 8,name: "Amuleto del Bosque", description: "Hace al portador invisible a las criaturas del bosque." },
        { rank: "C",index:58,durability: 20,totalDurability: 20,power: 12,name: "Cinturón de Agilidad", description: "Un cinturón que mejora la agilidad y destreza del usuario (x0.5)." },
    ],
    B: [
        { rank: "B",index:59,durability: 5,totalDurability: 5,power: 28,name: "Botas de Dash", description: "Botas que duplican la velocidad de movimiento del usuario durante un corto período de tiempo." },
        // { rank: "B",index:60,durability: 1,totalDurability: 1,power: 0,name: "Poción de Curacion Potente", description: "Una poción que es capaz de frenar cualquier herida o desangramiento al ser tomada." },
        // { ind60x:0,durability: 1,totalDurability: 1,power: 0,name: "Poción de Regeneración", description: "Una poción que es capaz de regenerar rapidamente al usuario durante un tiempo." },
        // { ind60x:0,durability: 10,totalDurability: 10,power: 14,name: "Poción de Vision Nocturna", description: "Una poción que permite ver perfectamente en la oscuridad cuando es ingerida." },
        // { ind60x:0,durability: 10,totalDurability: 10,power: 14,name: "Guantelete del Poder de las Almas", description: "Permite al portador capturar y usar fragmentos de almas para potenciar sus habilidades fisicas." },
        { rank: "B",index:60,durability: 18,totalDurability: 18,power: 24,name: "Espada de Plumas", description: "Permite convertirse en un ave momentaneamente y realizar ataques de gran filo." },
        { rank: "B",index:61,durability: 10,totalDurability: 10,power: 14,name: "Guantes de los Relámpagos", description: "Inflige un leve daño eléctrico con cada golpe, paralizando temporalmente a los enemigos." },
        // { ind60x:0,durability: 10,totalDurability: 10,power: 14,name: "Daga del Guardián de las Sombras", description: "Permite al portador moverse entre sombras, volviéndose indetectable en áreas oscuras." },
        { rank: "B",index:62,durability: 20,totalDurability: 20,power: 9,name: "Amuleto de la Determinación", description: "Aumenta la voluntad del portador, resistiendo encantamientos y maldiciones." },
        { rank: "B",index:63,durability: 12,totalDurability: 12,power: 11,name: "Capa del Gélido Viento", description: "Permite al portador moverse rápidamente en climas fríos, ignorando los efectos del frío extremo." },
        // { ind6x:0,durability: 10,totalDurability: 10,power: 14,name: "Cáliz del Guardián de la Muerte", description: "Permite al portador comunicarse brevemente con los muertos." },
        { rank: "B",index:64,durability: 13,totalDurability: 13,power: 11,name: "Cinturón de la Fortaleza Interior", description: "Refuerza la mente y el espíritu del portador, protegiéndolo de ataques psíquicos." },
        // { ind60x:0,durability: 10,totalDurability: 10,power: 14,name: "Túnica del Ilusionista", description: "Aumenta la efectividad y duración de las ilusiones creadas por el portador." },
        { rank: "B",index:65,durability: 3,totalDurability: 3,power: 40,name: "Arco Explosivo", description: "Dispara flechas explosivas parecidas a bullets potencia 2." },
        // { ind6x:0,durability: 10,totalDurability: 10,power: 14,name: "Brazaletes de la Amistad", description: "Permiten al portador sentir y localizar a sus amigos cercanos." },
        { rank: "B",index:66,durability: 30,totalDurability: 30,power: 0,cha:4,name: "Corona del Conquistador", description: "Aumenta el carisma." },
        { rank: "B",index:67,durability: 8,totalDurability: 8,power: 16,name: "Brazalete de la Guerra", description: "Aumenta la fuerza y resistencia del portador durante la batalla." },
        { rank: "B",index:68,durability: 6,totalDurability: 6,power: 15,name: "Guantes del Guardián del Trueno", description: "Permiten al portador lanzar chasquidos ensordecedores." },
        { rank: "B",index:69,durability: 2,totalDurability: 2,power: 18,name: "Orbe Cegadora", description: "Genera una luz cegadora que puede desorientar a los enemigos." },
        { rank: "B",index:70,durability: 15,totalDurability: 15,power: 12,name: "Capa del Guardián del Fuego", description: "Otorga inmunidad al fuego y aumenta la resistencia al calor extremo." },
        // { ind70x:0,durability: 10,totalDurability: 10,power: 14,name: "Anillo del Engaño", description: "Aumenta la habilidad del portador para mentir y engañar." },
        // { ind70x:0,durability: 10,totalDurability: 10,power: 14,name: "Orbe del Olvido", description: "Hace que el portador olvide un recuerdo traumático o doloroso." },
        { rank: "B",index:71,durability: 8,totalDurability: 8,power: 19,name: "Brazalete del Guerrero Férreo", description: "Aumenta la defensa física y resistencia del portador." },
        { rank: "B",index:72,durability: 7,totalDurability: 7,power: 10,name: "Amuleto del Lamento", description: "Permite al portador liberar un grito que aturde a los enemigos cercanos." },
        { rank: "B",index:73,durability: 8,totalDurability: 8,power: 19,name: "Daga de la Noche Eterna", description: "Causa ceguera temporal a aquellos que son heridos por ella." },
        // { ind70x:0,durability: 10,totalDurability: 10,power: 14,name: "Daga de la Tempestad", description: "Causa daño adicional durante tormentas o en ambientes lluviosos." },
        { rank: "B",index:74,durability: 13,totalDurability: 13,power: 17,name: "Lanza del Dragón", description: "Posee una alticima temperatura en su punta y puede emanar corrientes y disparos de fuego." },
        { rank: "B",index:75,durability: 99,totalDurability: 99,power: 1,name: "Amuleto de la Suerte", description: "Aumenta la probabilidad de éxito en situaciones arriesgadas." },
        { rank: "B",index:76,durability: 4,totalDurability: 4,power: 20,name: "Anillo de Invisibilidad Temporal", description: "Permite al portador volverse invisible durante 1 minuto, se desactiva al contacto." },
        // { ind70x:0,durability: 10,totalDurability: 10,power: 14,name: "Amuleto de Protección Psíquica", description: "Protege contra ataques mentales." },
        { rank: "B",index:77,durability: 20,totalDurability: 20,power: 5,name: "Anillo de Regeneración", description: "Sana lentamente las heridas del portador con el tiempo." },
        { rank: "B",index:78,durability: 20,totalDurability: 20,power: 0,cha:4,name: "Anillo del Conquistador", description: "Mejora la labia y el carisma." },
        { rank: "B",index:79,durability: 3,totalDurability: 3,power: 10,name: "Anillo de Protección Contra el Mal", description: "Protege un poco contra criaturas y hechizos oscuros." },
        { rank: "B",index:80,durability: 12,totalDurability: 12,power: 18,name: "Cetro de los Cuatro Elementos", description: "Permite al portador controlar fuego, agua, aire y tierra. Emitiendo el nombre del elemento, se genera un ataque predeterminado instantaneamente." },
        { rank: "B",index:81,durability: 18,totalDurability: 18,power: 10,name: "Collar del Equilibrio", description: "Mantiene al usuario equilibrado en cuerpo y mente, resistente a cambios de estado emocional." },
        { rank: "B",index:82,durability: 10,totalDurability: 10,power: 18,name: "Anillo de la Protección Elemental", description: "Proporciona resistencia a los cuatro elementos dependiendo del dedo en el que se coloca." },
        // { ind81x:0,durability: 10,totalDurability: 10,power: 14,name: "Botas de Caminante del Agua", description: "Permiten caminar sobre el agua como si fuera tierra firme." },
        { rank: "B",index:83,durability: 1,totalDurability: 1,power: 45,name: "Guantes de Fuerza Titánica", description: "Otorgan al usuario una fuerza descomunal durante 1 golpe." },
        { rank: "B",index:84,durability: 6,totalDurability: 6,power: 20,name: "Báculo del Trueno", description: "Lanza rayos que causan daño eléctrico a los enemigos." },
        // { ind81x:0,durability: 10,totalDurability: 10,power: 14,name: "Collar de Lenguas", description: "Permite al portador hablar y entender cualquier idioma." },
        { rank: "B",index:85,durability: 10,totalDurability: 10,power: 18,name: "Cinturón de los Gigantes", description: "Otorga temporalmente el tamaño y la fuerza de un gigante." },
        { rank: "B",index:86,durability: 8,totalDurability: 8,power: 23,name: "Espada de Hielo Eterno", description: "Congela todo lo que corta." },
        { rank: "B",index:87,durability: 18,totalDurability: 18,power: 16,name: "Espada de la Marea", description: "Una espada que se vuelve más poderosa en combate cerca del agua." },
        { rank: "B",index:88,durability: 15,totalDurability: 15,power: 22,name: "Espada del Viento Cortante", description: "Corta a través del aire, creando ráfagas de viento afiladas." },
        { rank: "B",index:89,durability: 10,totalDurability: 10,power: 11,name: "Escudo de Luz Sagrada", description: "Emite una luz brillante que repele a los no-muertos." },
        // { ind81x:0,durability: 10,totalDurability: 10,power: 10,name: "Anillo de Transformación", description: "Cambia temporalmente al portador en otra criatura. Siendo las posibilidades un perro, un slime o un goblin pequeño." },
        { rank: "B",index:90,durability: 6,totalDurability: 6,power: 17,name: "Bastón de Maldiciones", description: "Realiza maldiciones poderosas a distancia." },
        { rank: "B",index:91,durability: 5,totalDurability: 5,power: 12,name: "Corazón de Dragón", description: "Otorga al portador la capacidad de lanzar un aliento de dragón." },
        { rank: "B",index:92,durability: 15,totalDurability: 15,power: 12,name: "Capa del Dragón", description: "Proporciona resistencia al fuego y aumenta la intimidación." },
        // { ind92x:0,durability: 10,totalDurability: 10,power: 14,name: "Báculo de las Estaciones", description: "Permite cambiar el clima local temporalmente." },
        { rank: "B",index:93,durability: 20,totalDurability: 20,power: 11,name: "Escudo del León", description: "Aumenta la valentía y protege al portador de la magia oscura." },
        { rank: "B",index:94,durability: 22,totalDurability: 22,power: 12,name: "Daga de la Veneno Silencioso", description: "Envenena al enemigo sin dejar rastro del veneno." },
        // { ind92x:0,durability: 10,totalDurability: 10,power: 14,name: "Cáliz de la Verdad", description: "Obliga a quien bebe de él a decir solo la verdad." },
        // { ind92x:0,durability: 10,totalDurability: 10,power: 14,name: "Sombrero del Arlequín", description: "Permite al usuario engañar o divertir a cualquiera que lo vea." },
        { rank: "B",index:95,durability: 15,totalDurability: 15,power: 18,name: "Anillo del Guerrero", description: "Aumenta la resistencia física y mental en combate." },
        // { ind92x:0,durability: 10,totalDurability: 10,power: 14,name: "Capa de la Desaparición", description: "Hace que el portador sea completamente invisible mientras no se mueve." },
        // { ind92x:0,durability: 10,totalDurability: 10,power: 14,name: "Capa del Amanecer", description: "Brilla con la primera luz del día, curando heridas." },
        // { ind92x:0,durability: 10,totalDurability: 10,power: 14,name: "Anillo del Eco Místico", description: "Permite al portador replicar cualquier sonido que haya escuchado." },
        // { ind92x:0,durability: 10,totalDurability: 10,power: 14,name: "Báculo del Crepúsculo", description: "Genera una luz suave que calma a quienes la miran." },
        { rank: "B",index:96,durability: 12,totalDurability: 12,power: 16,name: "Daga del Viento Silencioso", description: "Golpea sin hacer ruido, ideal para ataques furtivos." },
        // { ind92x:0,durability: 10,totalDurability: 10,power: 14,name: "Brazalete de las Almas Perdidas", description: "Permite comunicarse con los espíritus de los difuntos." },
        // { ind92x:0,durability: 10,totalDurability: 10,power: 14,name: "Túnica del Enigma", description: "Esconde la verdadera identidad del portador, haciéndolo irreconocible." },
        // { ind92x:0,durability: 10,totalDurability: 10,power: 14,name: "Collar de la Voz Oculta", description: "Permite al portador hablar sin ser oído por alguien en especifico." },
        { rank: "B",index:97,durability: 13,totalDurability: 13,power: 15,name: "Espada del Trueno Rugiente", description: "Cada golpe emite un estruendo que aturde a los enemigos cercanos." },
        // { ind92x:0,durability: 10,totalDurability: 10,power: 14,name: "Cáliz de la Purificación", description: "Limpia cualquier líquido de impurezas y venenos." },
        // { rank: "B",index:0,durability: 10,totalDurability: 10,power: 14,name: "Cetro del Enfurecimiento", description: "Aumenta la agresividad de los enemigos cercanos hacia el portador." },
        { rank: "B",index:98,durability: 20,totalDurability: 20,power: 17,name: "Anillo del Espíritu Guardián", description: "Invoca un espíritu protector que lucha junto al portador." },
        { rank: "B",index:99,durability: 15,totalDurability: 15,power: 13,name: "Cinturón del Luchador", description: "Aumenta las habilidades en combate cuerpo a cuerpo." },
        // { ind98x:0,durability: 10,totalDurability: 10,power: 14,name: "Orbe del Refugio Seguro", description: "Crea una zona protegida donde el portador y sus aliados pueden descansar." },
        { rank: "B",index:100,durability: 15,totalDurability: 15,power: 10,name: "Daga de la Sombras", description: "Se vuelve más poderosa en combate al estar oculta en la oscuridad." },
        { rank: "B",index:101,durability: 8,totalDurability: 8,power: 15,name: "Cinturón de la Bestia", description: "Otorga la fuerza y la ferocidad de una bestia salvaje." },
        { rank: "B",index:102,durability: 30,totalDurability: 30,power: 4,name: "Sombrero del Guardián del Viento", description: "Permite al portador controlar pequeñas corrientes de aire." },
        // { rank: "B",index:0,durability: 10,totalDurability: 10,power: 14,name: "Botas de los Caminos Sin Fin", description: "Permiten viajar grandes distancias sin fatiga." },
    ],
    A: [
        { rank: "A",index:103,durability: 4,totalDurability: 4,power: 99,name: "Espada de la Muerte Silenciosa", description: "Asesina instantáneamente a un enemigo desprevenido." },
        // { rank: "A",index:104,durability: 1,totalDurability:1,power: 0,name: "Poción de Curacion Divina", description: "Una poción que es capaz de regenerar partes del cuerpo cuando es bebida." },
        { rank: "A",index:105,durability: 1,totalDurability: 1,power: 25,name: "Poción del Maestro Tortuga", description: "Una poción que hace al usuario tan resistente como una roca, anula dolor y reduce los daños recibidos durante 20 segundos." },
        { rank: "A",index:106,durability: 8,totalDurability: 8,power: 30,name: "Anillo de la Intangibilidad Breve", description: "Hace una porcion del portador intangible durante 5 segundos. Al terminar este tiempo si el usuario sigue atravesando algo, se prioriza la consistencia del portador, desmaterializando lo que se atravieza, pero desgastando el anillo." },
        { rank: "A",index:107,durability: 30,totalDurability: 30,power: 0,cha:7,name: "Sombrero del Conquistador", description: "Otorga carisma y autoridad, haciendo que el portador sea más persuasivo." },
        { rank: "A",index:108,durability: 25,totalDurability: 25,power: 17,name: "Lanza del Relámpago Furioso", description: "Descarga un poderoso rayo al impactar, causando daño adicional." },
        { rank: "A",index:109,durability: 20,totalDurability: 20,power: 15,name: "Escudo de la Tormenta", description: "Absorbe la energía de la electricidad, creando un escudo perfecto protector alrededor del portador." },
        { rank: "A",index:110,durability: 15,totalDurability: 15,power: 22,name: "Brazalete del Guardián de los Espíritus", description: "Protege al portador de eventos sorpresivos que no podria haber notado por medio de los sentidos comunes" },
        // { ind103x:0,durability: 10,totalDurability: 10,power: 18,name: "Escudo de la Mente Inquebrantable", description: "Protege al portador de ataques mentales y manipulación psíquica." },
        { rank: "A",index:111,durability: 17,totalDurability: 17,power: 17,name: "Daga de la Sangre", description: "Absorbe la vitalidad de aquellos a quienes hiere, curando al portador." },
        // { ind103x:0,durability: 10,totalDurability: 10,power: 18,name: "Túnica del Maestro Ilusionista", description: "Potencia las ilusiones, haciéndolas más difíciles de detectar y superar." },
        // { ind103x:0,durability: 10,totalDurability: 10,power: 18,name: "Daga del Guardián de las Profundidades", description: "Causa daño adicional a las criaturas del agua y otorga la habilidad de respirar bajo el agua." },
        // { ind103x:0,durability: 10,totalDurability: 10,power: 18,name: "Escudo del Guardián de las Sombras", description: "Absorbe la energía oscura, creando un escudo protector contra ataques sombríos." },
        // { ind103x:0,durability: 10,totalDurability: 10,power: 18,name: "Capa del Guardián de la Luz Estelar", description: "Otorga invisibilidad bajo la luz de las estrellas y aumenta la resistencia a los hechizos oscuros." },
        { rank: "A",index:112,durability: 5,totalDurability: 5,power: 20,name: "Escudo Reflejante", description: "Refleja hechizos de ataque de vuelta al lanzador, no lo reduce, provocandole daño como un escudo común." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 18,name: "Máscara de Ilusiones", description: "Permite al portador cambiar su apariencia." },
        { rank: "A",index:113,durability: 17,totalDurability: 17,power: 19,name: "Espada de la Luna", description: "Brilla en la oscuridad y es especialmente efectiva contra criaturas nocturnas, sombras o espiritus." },
        { rank: "A",index:114,durability: 19,totalDurability: 19,power: 23,name: "Guante de Telequinesis", description: "Permite mover objetos a una distancia de 10 metros con la mente." },
        // { ind113x:0,durability: 10,totalDurability: 10,power: 18,name: "Cáliz de la Fortuna", description: "Al beber de él, el portador recibe buena suerte durante un día." },
        // { ind113x:0,durability: 10,totalDurability: 10,power: 18,name: "Cáliz de la Fortuna", description: "Otorga al portador buena suerte durante un día. Pero..." },
        // { ind113x:0,durability: 10,totalDurability: 10,power: 18,name: "Manto de la Mente Clara", description: "Protege contra ataques psíquicos y controla emociones." },
        // { ind113x:0,durability: 10,totalDurability: 10,power: 18,name: "Espada del Guardián", description: "Permite al portador proteger a un aliado, absorbiendo su daño." },
        // { ind113x:0,durability: 10,totalDurability: 10,power: 18,name: "Botas de Sigilo Perfecto", description: "Permiten moverse sin hacer ruido alguno." },
        { rank: "A",index:115,durability: 25,totalDurability: 25,power: 15,name: "Báculo de los Espíritus", description: "Invoca espíritus aliados que ayudan en la batalla." },
        { rank: "A",index:116,durability: 99,totalDurability: 99,power: 0, map: true,name: "Brújula del Corazón", description: "Señala la dirección hacia la persona que el portador más desea encontrar." },
        { rank: "A",index:117,durability: 15,totalDurability: 15,power: 20,name: "Guantelete de Absorción de Magia", description: "Absorbe y almacena magia para una liberación posterior. Puede explotar." },
        // { ind113x:0,durability: 10,totalDurability: 10,power: 18,name: "Anillo de Salud Perfecta", description: "El portador es inmune a enfermedades, venenos o maldiciones, artefacto activo." },
        // { ind113x:0,durability: 10,totalDurability: 10,power: 18,name: "Gema de Visión Verdadera", description: "Permite ver a través de ilusiones y engaños mágicos de forma absoluta." },
        // { ind113x:0,durability: 10,totalDurability: 10,power: 18,name: "Botas de Gravedad", description: "Permiten caminar por techos y paredes cambiando la dirección de la gravedad relativa al usuario en los 3 ejes." },
        // { ind113x:0,durability: 10,totalDurability: 10,power: 18,name: "Anillo de los Sueños", description: "Permite entrar en los sueños de otros." },
        { rank: "A",index:118,durability: 5,totalDurability: 5,power: 28,name: "Guantelete del Martillo Explosivo", description: "Convierte un golpe en una poderosa explosión." },
        { rank: "A",index:119,durability: 16,totalDurability: 16,power: 20,name: "Espada de la Oscuridad", description: "Una espada que absorbe la luz y causa daño necrótico." },
        // { ind119x:0,durability: 10,totalDurability: 10,power: 18,name: "Cetro del Comando Mental", description: "Otorga la capacidad de dominar la voluntad de seres menores." },
        { rank: "A",index:120,durability: 18,totalDurability: 18,power: 24,name: "Capa del Cuervo", description: "Transforma al usuario en un cuervo, otorgándole vuelo temporal, duración de 1 minuto, cooldown de 1 segundo." },
        // { ind119x:0,durability: 10,totalDurability: 10,power: 18,name: "Collar de la Alquimia", description: "Convierte cosas en oro durante un tiempo." },
        { rank: "A",index:121,durability: 12,totalDurability: 12,power: 23,name: "Espada del Relámpago", description: "Lanza una descarga eléctrica al impactar." },
        { rank: "A",index:122,durability: 11,totalDurability: 11,power: 21,name: "Lanza de la Tormenta", description: "Causa daño eléctrico al impactar y puede llamar relámpagos del cielo." },
        // { ind119x:0,durability: 10,totalDurability: 10,power: 18,name: "Escudo de la Justicia", description: "Protege contra ataques deshonrosos o traicioneros." },
        // { ind119x:0,durability: 10,totalDurability: 10,power: 18,name: "Amuleto de la Serenidad", description: "Protege contra efectos de miedo y confusión." },
        { rank: "A",index:123,durability: 19,totalDurability: 19,power: 20,name: "Espada del Sol", description: "Brilla intensamente y repele a criaturas de la oscuridad, ademas de ser altamente efectiva contra espiritus." },
        // { ind119x:0,durability: 10,totalDurability: 10,power: 18,name: "Collar de la Ilusión", description: "Permite crear ilusiones detalladas y realistas a un solo objetivo durante un instante." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 18,name: "Sombrero de los Susurros", description: "Permite escuchar conversaciones lejanas sin ser detectado." },
        { rank: "A",index:124,durability: 8,totalDurability: 8,power: 27,name: "Anillo de la Furia Berserker", description: "Otorga al usuario una fuerza y resistencia extraordinarias en combate." },
        // { rank: "A",index:0,durability: 12,totalDurability: 10,power: 18,name: "Amuleto de la Voluntad de Hierro", description: "Protege contra la dominación y el control mental." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 18,name: "Anillo de la Detección de Secretos", description: "Revela pasajes ocultos y trampas en los alrededores." },
        { rank: "A",index:125,durability: 19,totalDurability: 19,power: 17,name: "Lanza del Relámpago", description: "Lanza relámpagos que dañan a múltiples enemigos a la vez." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 18,name: "Piedra de la Tranquilidad", description: "Calma las emociones de quienes estén cerca, evitando conflictos." },
        { rank: "A",index:126,durability: 1,totalDurability: 1,power: 60,name: "Cinturón de la Fuerza de los Ancestros Indora", description: "Permite realizar un destello a la máxima potencia posible para el usuario." },
        // { ind126x:0,durability: 10,totalDurability: 10,power: 18,name: "Guante de los Cielos", description: "Permite invocar tormentas o despejar los cielos a voluntad." },
        { rank: "A",index:127,durability: 15,totalDurability: 15,power: 20,name: "Espada de la Sangre Paralizante", description: "Al lamer la sangre de un oponente que pose sobre la espada, el objetivo se paralizará unos segundos." },
        { rank: "A",index:128,durability: 16,totalDurability: 16,power: 18,name: "Escudo del Guerrero Fantasma", description: "Invoca la protección de un guerrero fantasma para luchar al lado del portador." },
        // { ind126x:0,durability: 10,totalDurability: 10,power: 18,name: "Collar del Mar Profundo", description: "Permite respirar bajo el agua y comunicarse con criaturas acuáticas." },
        { rank: "A",index:129,durability: 11,totalDurability: 11,power: 17,name: "Anillo de la Ilusión Multiple", description: "Crea ilusiones hacia multiples enemigos a la vez durante un instante." },
        // { ind126x:0,durability: 10,totalDurability: 10,power: 18,name: "Espada de las Almas Gemelas", description: "Permite a dos usuarios compartir habilidades y vida durante la batalla." },
        // { ind126x:0,durability: 10,totalDurability: 10,power: 18,name: "Orbe de la Luz Celestial", description: "Destruye las criaturas oscuras al instante con su brillo." },
        { rank: "A",index:130,durability: 20,totalDurability: 20,power: 13,name: "Collar de la Serenidad", description: "Otorga paz mental y protege contra el miedo." },
        { rank: "A",index:131,durability: 15,totalDurability: 15,power: 15,name: "Báculo de la Orden Sagrada", description: "Invoca un círculo de protección sagrada alrededor del portador." },
        { rank: "A",index:132,durability: 19,totalDurability: 19,power: 16,name: "Guantelete del Trueno", description: "Desata una onda de choque eléctrica en el impacto." },
        { rank: "A",index:133,durability: 18,totalDurability: 18,power: 20,name: "Cinturón de las Montañas", description: "Otorga al portador una resistencia sobrehumana al daño físico." },
        // { ind132x:0,durability: 10,totalDurability: 10,power: 18,name: "Botas del Paso Ligero", description: "El portador no deja huellas ni hace ruido al caminar." },
        // { ind132x:0,durability: 10,totalDurability: 10,power: 18,name: "Collar del Ojo Vigilante", description: "Permite al portador ver lo que otros no pueden, incluso en la oscuridad total." },
        // { ind132x:0,durability: 10,totalDurability: 10,power: 18,name: "Amuleto de la Adivinación", description: "Permite ver destellos del futuro inmediato. Permitiendo ver 20 segundos en el futuro." },
        { rank: "A",index:134,durability: 20,totalDurability: 20,power: 15,name: "Sombrero del Espejismo", description: "Permite crear ilusiones a un objetivo." },
        // { ind132x:0,durability: 10,totalDurability: 10,power: 18,name: "Pergamino del Destino Cambiante", description: "Otorga al portador una oportunidad de reescribir un evento muy reciente, modificando el presente. Solo modifica 1 segundo al pasado." },
        // { ind132x:0,durability: 10,totalDurability: 10,power: 18,name: "Anillo del Reflejo Inverso", description: "Refleja ataques hacia su lanzador con un d4 de check." },
        { rank: "A",index:135,durability: 5,totalDurability: 5,power: 17,name: "Guante del Poder Elemental", description: "Controla y manipula un solo elemento a elección del portador. Permite una telekinesis del elemento y la formación del mismo." },
        { rank: "A",index:136,durability: 15,totalDurability: 15,power: 23,name: "Collar de la Gracia Élfica", description: "Aumenta la agilidad (x0.5) y la percepción del portador." },
        { rank: "A",index:137,durability: 19,totalDurability: 19,power: 15,name: "Lanza del Alba Radiante", description: "Causa daño adicional a las criaturas de la oscuridad, sombras, espiritus y no-muertos." },
        // { ind132x:0,durability: 10,totalDurability: 10,power: 18,name: "Orbe de la Conexión Mental", description: "Permite la comunicación telepática con otra mente cercana." },
        { rank: "A",index:138,durability: 18,totalDurability: 18,power: 20,name: "Anillo de la Tierra Movediza", description: "Permite crear lodazales de 1 metro de profundidad a una distancia de 7 metros." },
        // { ind132x:0,durability: 10,totalDurability: 10,power: 18,name: "Escudo de la Luz Lunar", description: "Brilla con la luz de la luna, protegiendo contra criaturas nocturnas." },
        { rank: "A",index:139,durability: 19,totalDurability: 19,power: 23,name: "Capa del Lince", description: "Otorga sentidos agudos y la habilidad de ver en la oscuridad." },
        { rank: "A",index:140,durability: 10,totalDurability: 10,power: 45,name: "Guantelete del Dragón", description: "Proporciona al portador una fuerza dracónica (x5) por tiempo de 5 segundos." },
        // { ind140x:0,durability: 10,totalDurability: 10,power: 18,name: "Anillo del Lazo Inquebrantable", description: "Permite al usuario compartir heridas y sanación con otro." },
        { rank: "A",index:141,durability: 40,totalDurability: 40,power: 5,name: "Espada de la Conquista", description: "Aumenta el carisma y la capacidad de liderazgo del portador en batalla." },
        { rank: "A",index:142,durability: 8,totalDurability: 8,power: 26,name: "Amuleto de la Resistencia", description: "Otorga una gran resistencia general." },
        // { ind140x:0,durability: 10,totalDurability: 10,power: 18,name: "Báculo del Guardián de las Cuevas", description: "Controla los insectos menores de las cuevas." },
        { rank: "A",index:143,durability: 20,totalDurability: 20,power: 35,name: "Capa de las Estrellas", description: "Permite aumentar las chances de destello al doble." },
        { rank: "A",index:144,durability: 30,totalDurability: 30,power: 22,name: "Guantes del Maestro de las Cadenas", description: "Permiten crear, controlar y manipular cadenas como si fueran extensiones del cuerpo." },
        // { ind140x:0,durability: 10,totalDurability: 10,power: 18,name: "Orbe del Agua Eterna Pura", description: "Genera agua pura. Tiene tiempo de recarga." },
        // { ind140x:0,durability: 10,totalDurability: 10,power: 18,name: "Orbe del Agua Eterna Potable", description: "Genera agua potable. Tiene tiempo de recarga." },
        { rank: "A",index:145,durability: 20,totalDurability: 20,power: 24,name: "Espada de la Venganza", description: "Causa daño adicional a aquellos que han herido al portador previamente. Con darle un toque con un dedo a la hoja, todos los ataques acumulados se liberan." },
        { rank: "A",index:146,durability: 7,totalDurability: 7,power: 20,name: "Túnica del Elementalista", description: "Otorga una gran resistencia sobre los elementos." },
        { rank: "A",index:147,durability: 20,totalDurability: 20,power: 18,name: "Guante de Maná Oscuro", description: "Posee una concentración de maná oscuro en el." },
        // { ind14x:0,durability: 10,totalDurability: 10,power: 18,name: "Amuleto del Guardián de los Espíritus", description: "Protege contra la posesión y las maldiciones espirituales." },
        { rank: "A",index:148,durability: 30,totalDurability: 30,power: 19,name: "Capa del Rayo", description: "Absorbe el daño eléctrico y lo libera en un ataque explosivo." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 18,name: "Anillo del Juicio", description: "Permite al portador discernir la verdadera naturaleza de las personas." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 18,name: "Báculo del Alba", description: "Genera una luz cegadora que daña a los no-muertos y limpia la oscuridad." },
        { rank: "A",index:149,durability: 25,totalDurability: 25,power: 23,name: "Espada de los Sueños", description: "Causa un sueño profundo en aquellos que son heridos por ella. Cada ataque ejercido por el usuario lo van durmiendo." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 18,name: "Escudo de la Fortaleza Mental", description: "Protege al portador contra ataques psíquicos y de control mental." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 18,name: "Anillo de la Empatía", description: "Permite sentir las emociones de quienes están cerca, artefacto activo, permite transmitir todos los sentimientos negativos hacia el usuario." },
        { rank: "A",index:150,durability: 20,totalDurability: 20,power: 20,name: "Cetro de la Tormenta", description: "Invoca una nube poderosa que obedece a las órdenes del portador y lo acompaña." },
        { rank: "A",index:151,durability: 22,totalDurability: 22,power: 19,name: "Guantelete del Alma Ardiente", description: "Permite al portador canalizar fuego a través de sus manos, dispararla y manipularla." },
        // { ind150x:0,durability: 10,totalDurability: 10,power: 18,name: "Capa del Guardián de la Luz", description: "Protege al portador de ataques oscuros, maldiciones o sombras." },
        // { ind150x:0,durability: 10,totalDurability: 10,power: 18,name: "Botas del Viajero Eterno", description: "Permiten al portador caminar sin descanso durante días sin fatigarse." },
        { rank: "A",index:152,durability: 16,totalDurability: 16,power: 24,name: "Anillo del Destino", description: "Ofrece al portador una visión de su futuro cercano o de los posibles futuros alternativos cercanos." },
        { rank: "A",index:153,durability: 18,totalDurability: 18,power: 22,name: "Túnica de la Niebla", description: "Genera una niebla densa que oculta al portador y a sus aliados." },
        // { ind150x:0,durability: 10,totalDurability: 10,power: 18,name: "Cáliz del Renacer", description: "Permite al portador recuperar una vez al día toda su energía vital." },
        // { ind150x:0,durability: 10,totalDurability: 10,power: 18,name: "Escudo del Relámpago", description: "Absorbe daño eléctrico y lo dispersa alrededor." },
        // { ind150x:0,durability: 10,totalDurability: 10,power: 18,name: "Cinturón del Guardián de las Profundidades", description: "Permite respirar bajo el agua y moverse con agilidad en el océano." },
        { rank: "A",index:154,durability: 15,totalDurability: 15,power: 20,name: "Báculo del Invierno Eterno", description: "Congela a los enemigos con un toque helado." },
        { rank: "A",index:155,durability: 20,totalDurability: 20,power: 21,name: "Anillo del Guardián de la Tierra", description: "Otorga control sobre pequeños temblores y la capacidad de abrir grietas en las paredes." },
        { rank: "A",index:156,durability: 12,totalDurability: 12,power: 24,name: "Capa del Murciélago", description: "Permite al portador convertirse en murciélago volar cortas distancias y ver en la oscuridad." },
        { rank: "A",index:157,durability: 7,totalDurability: 7,power: 25,name: "Guante del Relámpago", description: "Dispara rayos de energía eléctrica desde las manos del portador." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 18,name: "Báculo de la Vida", description: "Permite al portador curar heridas, revitalizar y curar a los enfermos." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 18,name: "Capa del Silencio", description: "Envuelve al portador en un silencio absoluto, haciéndolo imposible de detectar por el sonido, incluyendo su voz." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 18,name: "Lentes del Centinela", description: "Permite ver a través de paredes y otros obstáculos sólidos durante unos segundos, desgastando la vista." },
        { rank: "A",index:158,durability: 3,totalDurability: 3,power: 30,name: "Hierba del Hermitaño", description: "Permite entrar en la zona, un estado del destello en el que todo se ve más lento." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 18,name: "Báculo del Bosque", description: "Controla plantas y animales cercanos, permitiendote pedirles ayuda para combatir." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 18,name: "Cetro de la Oscuridad", description: "Controla sombras y puede crear oscuridad en salas y zonas." },
    ],
    S: [
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Cáliz del Fuego Eterno", description: "Permite lanzar un hechizo de fuego de potencia inhumana, recreando el potencial del conocido como Fire World." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Cáliz de Inmolación", description: "Permite lanzar un hechizo de fuego de potencia inhumana, recreando el potencial del conocido como Explosion (No se basa en el mana del usuario)." },
        { rank: "S",index:159,durability: 30,totalDurability: 30,power: 28,name: "Báculo Sagrado", description: "Un palo capaz de estirarse a 15 metros, golpea con dureza y brinda una mayor capacidad técnica en el combate." },
        { rank: "S",index:160,durability: 15,totalDurability: 15,power: 99,name: "Daga de la Hydra", description: "'Mientras más duro el objetivo, más corta'." },
        { rank: "S",index:161,durability: 1,totalDurability: 1,power: 70,name: "Poción del Dragón", description: "Una poción que convierte al usuario en un semi-dragon, creciendole alas y aumentar su temperatura corporal, dureza, resistencia, regeneración, aumento de fuerza. Ademas de brindarle capacidades de ataque de fuego." },
        { rank: "S",index:162,durability: 99,totalDurability: 99,power: 45,name: "Rifle STG", description: "No falla." },
        // { rank: "S",index:162,durability: 99,totalDurability: 99,power: 0,name: "Llave de las Sombras", description: "Abre todo lo que desees." },
        // { ind1S9x:0,durability: 10,totalDurability: 10,power: 25,name: "Amuleto de Resurrección", description: "Restaura la vida a un compañero caído una vez al día." },
        // { ind1S9x:0,durability: 10,totalDurability: 10,power: 25,name: "Capa del Manto Sombrío", description: "Permite al portador volverse una sombra durante 5 segundos." },
        // { ind1S9x:0,durability: 10,totalDurability: 10,power: 25,name: "Pergamino del Tiempo", description: "Permite retroceder el tiempo 15 segundos." },
        { rank: "S",index:163,durability: 4,totalDurability: 4,power: 30,name: "Reloj de Arena de la Eternidad", description: "Puede detener el tiempo durante 3 segundos." },
        { rank: "S",index:164,durability: 999,totalDurability: 999,power: 20,name: "Cinturón de la Resistencia Infinita", description: "Otorga resistencia infinita al cansancio físico." },
        // { ind159x:0,durability: 10,totalDurability: 10,power: 25,name: "Cáliz de la Curación", description: "Cura enfermedades y venenos cuando se bebe de él, curando al usuario de heridas también." },
        { rank: "S", index:104,durability: 20,totalDurability: 20,power: 14, vision: true,name: "Lentes de Visión del Maná", description: "Permite ver los flujos del maná por unos segundos." },
        // { ind159x:0,durability: 10,totalDurability: 10,power: 25,name: "Cubo de Teletransporte", description: "Permite al usuario y compañeros transportarse a un lugar conocido al activarlo, permite un solo uso, sin importar la distancia." },
        // { ind159x:0,durability: 10,totalDurability: 10,power: 25,name: "Tomo de Sabiduría Antigua", description: "Contiene conocimientos ocultos que invaden al lector, siendo asesorado por voces en su cabeza para tener ideas." },
        // { ind159x:0,durability: 10,totalDurability: 10,power: 25,name: "Cetro del Caos", description: "Lanza magia aleatoria cada vez que se usa." },
        { rank: "S",index:165,durability: 15,totalDurability: 15,power: 27,name: "Amuleto del Arquero Mágico", description: "Todos los proyectiles lanzados se redirigen a los enemigos de forma absoluta." },
        { rank: "S",index:166,durability: 15,totalDurability: 15,power: 29,name: "Báculo del Tiempo", description: "Permite ralentizar o acelerar el tiempo brevemente." },
        // { ind1S6x:0,durability: 10,totalDurability: 10,power: 25,name: "Collar de las Estrellas", description: "Permite al usuario invocar meteoritos que caen del cielo." },
        // { ind1S6x:0,durability: 10,totalDurability: 10,power: 25,name: "Piedra de Telepatía", description: "Permite comunicarse mentalmente, la información transmitida supera el metagaming." },
        // { ind1S6x:0,durability: 10,totalDurability: 10,power: 25,name: "Anillo de Adivinación", description: "Permite ver brevemente el futuro cercano, permitiendote predecir el accionar de un enemigo, artefacto activo." },
        { rank: "S",index:167,durability: 5,totalDurability: 5,power: 50,name: "Anillo del Poder Divino", description: "Otorga habilidades de no-muerto de luz temporalmente." },
        { rank: "S",index:168,durability: 14,totalDurability: 14,power: 32,name: "Guantes de Teletransportación", description: "Permite intercambiar posiciones con una persona u objeto a una distancia de 15 metros instantáneamente al realizar un aplauso." },
        { rank: "S",index:169,durability: 15,totalDurability: 15,power: 20,name: "Llave del Limbo", description: "Abre cualquier puertas dimensionales, permitiendo el viaje entre planos temporalmente." },
        { rank: "S",index:170,durability: 99,totalDurability: 99,power: 30,name: "Alabarda de Vigor Inquebrantable", description: "Mientras la uses sentirás que nada puede frenarte, ni nada puede matarte. 'No morirás, no importa que tu cuerpo sea destruido por completo. Tus deseos de pelear te levantarán porque son muy grandes.', el guión te imbuirá y mientras ese corazón bombee, 'los derrotarás, pase lo que pase.'" },
        { rank: "S",index:171,durability: 13,totalDurability: 13,power: 60,name: "Cinturón del Monje Celestial", description: "Aumenta las habilidades físicas y espirituales del portador, triplicando las chances de destello." },
        { rank: "S",index:172,durability: 9,totalDurability: 9,power: 20,name: "Sombrero del Limbo", description: "Permite al usuario cruzar entre planos de existencia temporalmente, accediendo al Limbo." },
        { rank: "S",index:173,durability: 20,totalDurability: 20,power: 16,name: "Guante de la Agarre Mortal", description: "Asegura que el portador nunca suelte lo que agarra." },
        // { rankS "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Cáliz de la Resurrección Oscura", description: "Revive a los muertos, pero con un daño en su alma." },
        { rank: "S",index:174,durability: 3,totalDurability: 3,power: 70,name: "Túnica de las Estrellas Fugaces", description: "Permite al portador moverse rápidamente como un meteoro, permitiendo el uso del destello 3 veces de forma absoluta." },
        // { rankS "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Sombrero del Encantador", description: "Brinda la habilidad para crear tres artefactos mágicos que puedas llevarte a la realidad, solo de rango A para abajo." },
        // { rankS "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Aretes de la Fusión", description: "Al dos usuarios colocarse uno en su oreja opuesta, estos se fusionarán instantaneamente, brindando capacidades superiores en todos los sentidos. La fusión dura 5 minutos." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Brazaletes de la Eternidad", description: "Otorgan un rejuvenecimiento continuo, retrasando el envejecimiento y curando heridas." },
        { rank: "S",index:175,durability: 5,totalDurability: 5,power: 25,name: "Anillo del Tiempo Detenido", description: "Permite detener el tiempo brevemente para una acción rápida. Para activarlo es necesario pronunciar: 'The World'. Segun mas roto esté, mas tiempo durará, llegando a un limite de 10 segundos en su último uso." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Sombrero del Mago Errante", description: "Permite crear abismos, con sus consecuencias." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Cáliz de la Transformación", description: "Permite cambiar la forma física del portador temporalmente a cualquier especie." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Guantes del Control Mental", description: "Otorgan la capacidad de manipular mentalmente a un solo objetivo. Cuando es tocado, el objetivo se vuelve tu aliado." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Anillo del Olvido", description: "Hace que aquellos que el portador toque olviden la última hora. Efectivo una sola vez por dia." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Cinturón del Guardián de las Llaves", description: "Permite al portador abrir cualquier cerradura con un dado de d4, si sale 4, abre la cerradura." },
        // { rank: "A",index:0,durability: 3,totalDurability: 3,power: 25,name: "Collar del Mono Inmortal", description: "Otorga 3 vidas al portador, por cada una brinda un efecto especial, siendo este aleatorio, estos son: Invisibilidad (1s), Duplicación de chance de destello (3), Limbo (3s)." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Escudo del Espejo", description: "Refleja cualquier ataque de cualquier tipo hacia el lanzador, en caso de proyectil, se devuelve." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Amuleto del Antiguo Yo", description: "Te permite cambiar tu cuerpo momentaneamente al mejor estado fisico que has poseido, valorandolo por su capacidad de combate y mágica. Un solo uso, el estado se terminará dependiendo del maná desgastado en recrear el antiguo Yo." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Anillo del Caos", description: "Al ser activado, la realidad pierde sentido por unos breves segundos, ocurriendo cosas imposibles." },
        { rank: "S",index:176,durability: 99,totalDurability: 99,power: 17,name: "Guantes de Vinculación del Hechicero Errante", description: "Permiten la creacion de magia encriptada con movimientos de la mano." },
        { rank: "S",index:177,durability: 99,totalDurability: 99,power: 20,name: "Guantes de Vinculación del Guerrero Errante", description: "Permiten la creacion de armas de Luz." },
        { rank: "S",index:178,durability: 15,totalDurability: 15,power: 22,name: "Brazalete de la Dualidad", description: "Permite al portador duplicar su imagen para confundir a los enemigos. El clon es real y es controlado por el original." },
        { rank: "S",index:179,durability: 6,totalDurability: 6,power: 50,name: "Túnica de la Magia Prohibida", description: "Otorga acceso a hechizos oscuros y poderosos, pero a un alto costo." },
        { rank: "S",index:180,durability: 6,totalDurability: 6,power: 33,name: "Guantelete del Guardián de la Gravedad", description: "Permite al portador manipular la gravedad a su alrededor, levantando objetos pesados o brindando levitación a quien desee." },
        { rank: "S",index:181,durability: 20,totalDurability: 20,power: 20,name: "Guantes del Guardián del Viento", description: "Controla los vientos, permitiendo al portador invocar ráfagas poderosas y poder impulsarse fuertemente con ellas." },
        { rank: "S",index:182,durability: 18,totalDurability: 18,power: 22,name: "Guantes del Chasquido de Fuego", description: "Permite manipular llamas con gran poder generadas a partir de chascar los dedos." },
        { rank: "S",index:183,durability: 14,totalDurability: 14,power:37,name: "Guantes del Mago Elemental", description: "Permiten al portador canalizar y lanzar hechizos de todos los elementos del nivel de los magos ancestrales." },
        // { ind1S0x:0,durability: 10,totalDurability: 10,power: 25,name: "Orbe de la Eternidad", description: "Almacena el tiempo en su interior, permitiendo al portador ralentizar su paso en su perspectiva." },
        { rank: "S",index:184,durability: 10,totalDurability: 10,power: 25,name: "Espada del Guardián Eterno", description: "Proporciona protección continua al portador, creando un escudo mágico alrededor por sala." },
        { rank: "S",index:185,durability: 24,totalDurability: 24,power: 18,name: "Botas del Caminante Aereo", description: "Permiten al portador caminar sobre el aire." },
        { rank: "S",index:186,durability: 14,totalDurability: 14,power: 36,name: "Anillo de la Nube Voladora", description: "Permiten al portador invocar una nube y subirse en ella." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Sombrero del Guardián de la Verdad", description: "Revela las mentiras y falsedades en su entorno cercano, artefacto activo. Cuando se usa se obtendrá la información." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Saco de Runas", description: "Obliga a tirar un d6 por sala de combate para chances de drop de runas, x<8 chances de romperse." },
        { rank: "S",index:187,durability: 3,totalDurability: 3,power: 70,name: "Guante del Silencio Magico", description: "Permite al portador anular cualquier tipo de magia antes de que pueda lanzarse." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Brazalete del Guardián de la Vida", description: "Otorga regeneración acelerada de heridas y curación instantánea de heridas leves." },
        { rank: "S",index:188,durability: 9,totalDurability: 9,power: 24,name: "Guantes del Limbo", description: "Permiten al portador crear portales temporales para pasar de plano." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Orbe de la Oscuridad Abisal", description: "Crea un agujero negro en un punto del espacio elegido, todo lo cercano es absorbido sin dejar excepciones. Usar con precausion." },
        // { rank: "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Sombrero del Maestro de las Marionetas", description: "Permite al portador controlar a otros como si fueran marionetas al tocarlos, uno a la vez, puede dañar la cordura del usuario." },
        { rank: "S",index:189,durability: 5,totalDurability: 5,power: 60,name: "Escudo de Zoleus", description: "Crea una barrera impenetrable de luz embuida con magia de Zoleus que bloquea todo tipo de ataques enemigos." },
        { rank: "S",index:190,durability: 25,totalDurability: 25,power: 19,name: "Cinturón del Guardián de la Tierra", description: "Permite al portador manipular la tierra y crear terremotos." },
        { rank: "S",index:191,durability: 16,totalDurability: 16,power: 27,name: "Guante del Guardián de las Llamas", description: "Controla el fuego, permitiendo lanzar llamas o extinguirlas a voluntad." },
        // { ind1S1x:0,durability: 10,totalDurability: 10,power: 25,name: "Anillo del Guardián de la Fortuna", description: "Permite al 'jugador' usar un dado extra cada vez que tira el d20, pero siendo incapaz de tirar el mismo que tiro anteriormente sin haber tirado el resto una vez antes." },
        // { ind1S1x:0,durability: 10,totalDurability: 10,power: 25,name: "Anillo de la Culpa Compartida", description: "Permite al 'jugador' juntar el resultado de tirar el d10 entre los jugadores totales, teniendo un limite de player*10 en lugar de 20." },
        // { ind1S1x:0,durability: 10,totalDurability: 10,power: 25,name: "Báculo del Guardián de los Espíritus", description: "Permite al portador invocar y controlar espíritus malévolos y hacer pactos con ellos para obtener un uso de un artefacto aleatorio de rango S. El precio a pagar es alto." },
        { rank: "S",index:192,durability: 20,totalDurability: 20,power: 27,name: "Espada del Eco", description: "Cada corte hecho queda registrado en el oponente, al realizar un toque a la hoja de la espada se hace una repetición del ataque." },
        // { ind1S1x:0,durability: 10,totalDurability: 10,power: 25,name: "Escudo del Guardián de la Luz", description: "Te hace inmune a todo ataque oscuro, desde maldiciones hasta simples espiritus o sombras." },
        { rank: "S",index:193,durability: 5,totalDurability: 5,power: 50,name: "Guante del Heroe Mago Antiguo", description: "Permite al portador lanzar rayos y controlar la electricidad a voluntad. La electricidad permite una leve levitación." },
        { rank: "S",index:194,durability: 8,totalDurability: 8,power: 40,name: "Botas del Guardián del Viento", description: "Permiten al portador correr a velocidades increíbles, como si fuera un vendaval, cuadruplicando la velocidad de movimiento." },
        { rank: "S",index:195,durability: 20,totalDurability: 20,power: 20,name: "Amuleto del Guardián del Bosque", description: "Concede la capacidad de comunicarse con los animales y las plantas del bosque. En bosques, te permite controlar las raices de los arboles para atacar, mas lento que un Trent." },
        // { rankS "A",index:0,durability: 10,totalDurability: 10,powe25: 0,name: "Piedra Filosofal", description: "Permite capturar y almacenar almas, otorgando todo tipo de poderes al portador, como la curación instantanea, magias antiguas, telekinesis y levitación. Pero a un gran costo." },
        // { rankS "A",index:0,durability: 10,totalDurability: 10,powe25: 0,name: "Lámpara de los Espíritus", description: "Permite invocar un genio al que podes hacerle 3 preguntas." },
        // { rankS "A",index:0,durability: 10,totalDurability: 10,power: 25,name: "Anillo del Guardián del Inframundo", description: "Permite influir una tortura mental eterna a quien se desee, con solo apuntarlo." },
        { rank: "S",index:196,durability: 20,totalDurability: 20,power: 29,name: "Báculo del Guardián del Hielo", description: "Permite al portador un control perfecto del hielo, permitiendo congelar cosas y crear hielo de la nada." },
        { rank: "S",index:197,durability: 10,totalDurability: 10,power: 25,name: "Anillo del Guardián de la Eternidad", description: "Otorga al portador la capacidad de detener el tiempo durante 1 segundo para el y sus compañeros." },
        { rank: "S",index:198,durability: 999,totalDurability: 999,power: 99,name: "La Espada Legendaria, Trilybur", description: "Una espada milenaria que proviene de mundos desconocidos, posee unas capacidades casi divinas." },
        { rank: "S",index:199,durability: 70,totalDurability: 70,power: 80,name: "La Espada Ilusoria, Liebor", description: "Una espada capaz de realizar ilusiones de un altisimo calibre, pudiendo crear un bosque entero para tapar una ciudad, como ya ha hecho." },
        { rank: "S",index:200,durability: 40,totalDurability: 40,power: 60,name: "La Espada fuera de su Lugar", description: "Una espada capaz de impulsar al jugador a altas velocidades y brindarle una gran resistencia." },
        // { rank: "S",index:0,durability: 10,totalDurability: 10,power: 25,name: "Sombrero del Guardián de los Secretos", description: "Permite al portador descubrir secretos ocultos y desvelar misterios, artefacto activo." },
    ]
}