import { faBomb, faBook, faBookmark, faBowlFood, faCannabis, faCoins, faCompass, faCreditCard, faCrown, faCube, faExplosion, faFile, faFire, faGavel, faGem, faGenderless, faGlasses, faGlobe, faHandcuffs, faHands, faHatCowboySide, faHeart, faHourglass, faKey, faLock, faMagicWandSparkles, faMartiniGlass, faMasksTheater, faMedal, faMitten, faOilCan, faRibbon, faRing, faSackXmark, faScroll, faShield, faShirt, faSleigh, faSocks, faTableCells, faVial, faVials, faWandMagic, faWineBottle } from "@fortawesome/free-solid-svg-icons";
import { router } from "../vite-env";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

import { FaBow, FaDagger, FaRifle, FaSword } from '../assets/svg/sword-svgrepo-com';

export const iconSelectorObj: router = {
    Daga: <FaDagger />,
    La: <FaSword />,
    Espada: <FaSword />,
    Rifle: <FaRifle />,
    Arco: <FaBow />,
    Libro: <FontAwesomeIcon icon={faBook} />,
    Credit: <FontAwesomeIcon icon={faCreditCard} />,
    Carta: <FontAwesomeIcon icon={faFile} />,
    Bomba: <FontAwesomeIcon icon={faBomb} />,
    Moneda: <FontAwesomeIcon icon={faCoins} />,
    Poción: <FontAwesomeIcon icon={faVial} />,
    Candado: <FontAwesomeIcon icon={faLock} />,
    Saco: <FontAwesomeIcon icon={faSackXmark} />,
    Velas: <FontAwesomeIcon icon={faFire} />,
    Olla: <FontAwesomeIcon icon={faSleigh} />,
    Red: <FontAwesomeIcon icon={faTableCells} />,
    Raciones: <FontAwesomeIcon icon={faBowlFood} />,
    Anillo: <FontAwesomeIcon icon={faRing} />,
    Capa: <FontAwesomeIcon icon={faShirt} />,
    Armadura: <FontAwesomeIcon icon={faShirt} />,
    Ropa: <FontAwesomeIcon icon={faShirt} />,
    Pedernal: <FontAwesomeIcon icon={faFire} />,
    Manta: <FontAwesomeIcon icon={faBookmark} />,
    Frascos: <FontAwesomeIcon icon={faVials} />,
    Martillo: <FontAwesomeIcon icon={faGavel} />,
    Hacha: <FontAwesomeIcon icon={faGavel} />,
    Escudo: <FontAwesomeIcon icon={faShield} />,
    Guantes: <FontAwesomeIcon icon={faHands} />,
    Botas: <FontAwesomeIcon icon={faSocks} />,
    Báculo: <FontAwesomeIcon icon={faMagicWandSparkles} />,
    Bastón: <FontAwesomeIcon icon={faMagicWandSparkles} />,
    Varita: <FontAwesomeIcon icon={faMagicWandSparkles} />,
    Collar: <FontAwesomeIcon icon={faMedal} />,
    Explosivos: <FontAwesomeIcon icon={faExplosion} />,
    Llave: <FontAwesomeIcon icon={faKey} />,
    Orbe: <FontAwesomeIcon icon={faGlobe} />,
    Aro: <FontAwesomeIcon icon={faGenderless} />,
    Hierba: <FontAwesomeIcon icon={faCannabis} />,
    Brazaletes: <FontAwesomeIcon icon={faHandcuffs} />,
    Aretes: <FontAwesomeIcon icon={faHandcuffs} />,
    Sombrero: <FontAwesomeIcon icon={faHatCowboySide} />,
    Cinturón: <FontAwesomeIcon icon={faRibbon} />,
    Vendas: <FontAwesomeIcon icon={faRibbon} />,
    Cuerda: <FontAwesomeIcon icon={faRibbon} />,
    Amuleto: <FontAwesomeIcon icon={faGenderless} />,
    Lámpara: <FontAwesomeIcon icon={faOilCan} />,
    Pergamino: <FontAwesomeIcon icon={faScroll} />,
    Medallón: <FontAwesomeIcon icon={faMedal} />,
    Botella: <FontAwesomeIcon icon={faWineBottle} />,
    Corona: <FontAwesomeIcon icon={faCrown} />,
    Reloj: <FontAwesomeIcon icon={faHourglass} />,
    Máscara: <FontAwesomeIcon icon={faMasksTheater} />,
    Guante: <FontAwesomeIcon icon={faMitten} />,
    Manto: <FontAwesomeIcon icon={faShirt} />,
    Cáliz: <FontAwesomeIcon icon={faMartiniGlass} />,
    Cubo: <FontAwesomeIcon icon={faCube} />,
    Brújula: <FontAwesomeIcon icon={faCompass} />,
    Piedra: <FontAwesomeIcon icon={faGem} />,
    Runa: <FontAwesomeIcon icon={faGem} />,
    Tomo: <FontAwesomeIcon icon={faScroll} />,
    Colgante: <FontAwesomeIcon icon={faMedal} />,
    Gema: <FontAwesomeIcon icon={faGem} />,
    Corazón: <FontAwesomeIcon icon={faHeart} />,
    Cetro: <FontAwesomeIcon icon={faMagicWandSparkles} />,
    Lentes: <FontAwesomeIcon icon={faGlasses} />,
    Guantelete: <FontAwesomeIcon icon={faMitten} />,
    Túnica: <FontAwesomeIcon icon={faShirt} />,
    Lanza: <FontAwesomeIcon icon={faWandMagic} />,
    Antorcha: <FontAwesomeIcon icon={faFire} />,
    Alabarda: <FontAwesomeIcon icon={faWandMagic} />,
    Brazalete: <FontAwesomeIcon icon={faHandcuffs} />,
}
